# Generated by Django 2.0.3 on 2020-01-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Article',
            new_name='article',
        ),
    ]
